-- Member profile information.
create table if not exists public.profiles (
    id uuid primary key
        references auth.users(id)
        on delete cascade,

    display_name text not null
        check (
        char_length(display_name) between 1 and 80
        ),

    wellness_goal text not null
        default 'Explore drinks',

    created_at timestamptz not null
        default now(),

    updated_at timestamptz not null
        default now()
);

-- Recipes saved by authenticated members.
create table if not exists public.favorites (
    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    drink_id text not null,
    drink_name text not null,
    drink_image text,
    category text,

    created_at timestamptz not null
        default now(),

    primary key (user_id, drink_id)
);

create index if not exists favorites_user_id_index
    on public.favorites(user_id);

-- Messages submitted through the public contact form.
create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    name text not null
        check (char_length(name) between 1 and 80),
    email text not null
        check (char_length(email) between 3 and 254),
    message text not null
        check (char_length(message) between 1 and 1000),
    created_at timestamptz not null default now()
);

alter table public.profiles
    enable row level security;

alter table public.favorites
    enable row level security;

alter table public.contact_messages
    enable row level security;

drop policy if exists
    "Visitors can submit contact messages"
    on public.contact_messages;

create or replace function public.submit_contact_message(
    submitter_name text,
    submitter_email text,
    submitted_message text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
    if exists (
        select 1
        from public.contact_messages
        where lower(email) = lower(trim(submitter_email))
          and created_at > now() - interval '5 minutes'
    ) then
        return false;
    end if;

    insert into public.contact_messages (name, email, message)
    values (
        trim(submitter_name),
        lower(trim(submitter_email)),
        trim(submitted_message)
    );

    return true;
end;
$$;

revoke all
    on function public.submit_contact_message(text, text, text)
    from public;

grant execute
    on function public.submit_contact_message(text, text, text)
    to anon, authenticated;

drop policy if exists
    "Members can read their profile"
    on public.profiles;

create policy
    "Members can read their profile"
    on public.profiles
    for select
    to authenticated
    using (auth.uid() = id);


drop policy if exists
    "Members can create their profile"
    on public.profiles;

create policy
    "Members can create their profile"
    on public.profiles
    for insert
    to authenticated
    with check (auth.uid() = id);


drop policy if exists
    "Members can update their profile"
    on public.profiles;

create policy
    "Members can update their profile"
    on public.profiles
    for update
    to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);


drop policy if exists
    "Members can delete their profile"
    on public.profiles;

create policy
    "Members can delete their profile"
    on public.profiles
    for delete
    to authenticated
    using (auth.uid() = id);

drop policy if exists
    "Members can read their favorites"
    on public.favorites;

create policy
    "Members can read their favorites"
    on public.favorites
    for select
    to authenticated
    using (auth.uid() = user_id);


drop policy if exists
    "Members can add favorites"
    on public.favorites;

create policy
    "Members can add favorites"
    on public.favorites
    for insert
    to authenticated
    with check (auth.uid() = user_id);


drop policy if exists
    "Members can update favorites"
    on public.favorites;

create policy
    "Members can update favorites"
    on public.favorites
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);


drop policy if exists
    "Members can delete favorites"
    on public.favorites;

create policy
    "Members can delete favorites"
    on public.favorites
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- Allows an authenticated member to permanently delete their own account.
create or replace function public.delete_account()
returns void
language sql
security definer
set search_path = ''
as $$
    delete from auth.users
    where id = auth.uid();
$$;

revoke all
    on function public.delete_account()
    from public;

grant execute
    on function public.delete_account()
    to authenticated;
